"""Add brand_id foreign key to products

Revision ID: 2fa6dc1b8e92
Revises: 5e7b5b00bfab
Create Date: 2025-06-27 18:15:45.055376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa6dc1b8e92'
down_revision: Union[str, None] = '5e7b5b00bfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
